server:
  port: 8080

spring:
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  datasource:
    url: jdbc:postgresql://192.168.10.114:5432/test
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  data:
    redis:
      host: 192.168.10.114
      port: 6379
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3.5:9b
          temperature: 0.7
          top-p: 0.9

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

file:
  upload-dir: E:/Document/MyObject/SpringBootTemplate/uploads/